added email verification
SachkovTech/sachkov-tech-backend pull request #118
Opened 2024-12-07 16:16 UTC by aznoran

2024-12-07 16:59 UTC, KirillSachkov requested changes

2024-12-07 16:59 UTC, KirillSachkov commented on NotificationService/src/NotificationService/Consumers/UserRegisteredEventConsumer.cs
> +    private const string ACCOUNT_SERVICE_API_URL = "http://localhost:5273/api/Accounts/";
это в appsettings

2024-12-07 16:59 UTC, KirillSachkov commented on NotificationService/src/NotificationService/Consumers/UserRegisteredEventConsumer.cs
> +    private const string ACCOUNT_SERVICE_VERIFYING_EMAIL_ENDPOINT = "email-verification/";
account service должен присылать готовую ссылку для подтверждения, там уже будет ссылка на endpoint и code

2024-12-07 16:59 UTC, KirillSachkov commented on NotificationService/src/NotificationService/Consumers/UserRegisteredEventConsumer.cs
> +        var client = Client;
зачем?

2024-12-07 16:59 UTC, KirillSachkov commented on NotificationService/src/NotificationService/Consumers/UserRegisteredEventConsumer.cs
> +            throw new Exception("Failed to get user info from Account service: " + payload.Errors);
вот это всё взаимодействие через http нужно чтобы было в проекте Accounts.Communication, который должен подтягиваться через nuget. Пример в FileService.Communication

2024-12-07 16:59 UTC, KirillSachkov commented on NotificationService/src/NotificationService/HttpClientSource/HttpClientSource.cs
> +}
никогда так не используй httpclient, нужно его регистрировать в di. Есть пример в FileService.Communication

2024-12-07 16:59 UTC, KirillSachkov commented on backend/src/Accounts/SachkovTech.Accounts.Presentation/Providers/HttpContextProvider.cs
> +    }
Уже есть UserScopedData, пример в AccountController StartUploadPhoto

2024-12-07 18:33 UTC, aznoran commented
все работает - верификация пройдена, что делать с BASE_URL понятия не имею, ладно еще в хендлере я могу вытащить без проблем я просто спешил, но что делать с AccountsHttpClient хз там оно не подтягивает ни в какую а пушить нугеты каждую секунду новую версию тоже очень много времени занимает, делал точь в точь как файл сервис можешь сам удостовериться

2024-12-08 11:02 UTC, aznoran commented
TODO: написать тесты (это комментарий для себя)

2024-12-08 11:37 UTC, KirillSachkov approved these changes

2024-12-08 11:37 UTC, merged