Added configurations and CRUD
SachkovTech/sachkov-tech-backend pull request #148
Opened 2024-12-19 12:06 UTC by YaraOduvanchik

2025-01-06 15:16 UTC, KirillSachkov requested changes

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.API/Controllers/Requests/CreateAchievementForIssueRequest.cs
> +    IssueConditionDto LessonCondition,
Issue или Lesson определитесь

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.Application/Features/Achievement/Commands/Create/ForIssue/CreateAchievementForIssueCommand.cs
> +public record CreateAchievementForIssueCommand(
Лучше всё это переиненовать в стиле CreateIssueAchievement, CreateLessonAchievement и так везде

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.Application/Features/Achievement/Commands/Create/ForIssue/CreateAchievementForIssueHandler.cs
> +        var achievement = Domain.Achievements.Achievement.Create(
Domain.Achievements.Achievement. стрёмно как-то выглядит

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.Application/Interfaces/IDbContext.cs
> +    public DbSet<UserProgress> UserProgresses { get; }
здесь лучше IQueriable сделать

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.Application/Responses/AchievementResponse.cs
> +    public Guid AchievementId { get; init; }
просто Id

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.Domain/ValueObjects/Conditions/IssueCondition.cs
> +    [JsonConstructor]
это обязательно? мб сделать пустой конструктор

2025-01-06 15:16 UTC, KirillSachkov commented on UserProgressService/src/UserProgressService.Infrastructure/Condiguration/Converters/ConditionJsonConverter.cs
> +}
что-то страшное, вот с этой секунды посмотрите видео -https://www.youtube.com/watch?v=xpm2nRpvvA8&t=667s

и переделайте конвертацию condition по-человечески

2025-01-07 14:06 UTC, YaraOduvanchik commented on UserProgressService/src/UserProgressService.Infrastructure/Condiguration/Converters/ConditionJsonConverter.cs
> +}
Мы отрефакторили немного конвертер, если писать маппер из видео, код будет примерно такой-же, но раскиданный по разным файлам

2025-01-08 01:29 UTC, aznoran commented
Зачем Converter? можно использовать обычный Newtonsoft.Json.

2025-01-08 01:32 UTC, aznoran commented
зачем менять Nuget.Config? тот комментарий используется для того что инициализировать xml разметку, а этот файл её использует, может и опционально, но оставьте её лишним не будет

2025-01-08 01:33 UTC, aznoran commented
случайно обновил ветку но все равно пришлось бы

2025-01-08 12:19 UTC, KirillSachkov approved these changes

2025-01-08 12:43 UTC, merged