Savchenko/dev 28
SachkovTech/sachkov-tech-backend pull request #2
Opened 2024-10-20 15:54 UTC by aznoran

2024-10-20 15:55 UTC, aznoran commented
- [ ]

2024-10-20 15:55 UTC, aznoran commented
случайно

2024-10-21 10:53 UTC, KirillSachkov requested changes

2024-10-21 10:53 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Application/Commands/Approve/ApproveIssueReviewHandler.cs
> +    private readonly IIssueSolvingContract _contract;
нужно везде уточнять, что за контракт мы используем, их может быть несколько, в данном случае _issueSolvingContract

2024-10-21 10:53 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Application/Commands/SendForRevision/SendForRevisionHandler.cs
> +        }
давай эту проверку делать внутри домена

2024-10-21 10:53 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Infrastructure/Repositories/IssueReviewRepository.cs
> +    public async Task<Result<IssueReview, Error>> GetByIdWithComments(IssueReviewId id,
этого метода не должно быть, так как issuereview это агрегат(этот модуль делаем по ddd) и мы всегда должны доставать его полностью, включая комментарии, нужно доработать метод GetById

2024-10-21 11:08 UTC, KirillSachkov approved these changes

2024-10-21 11:09 UTC, merged