added user scoped data
SachkovTech/sachkov-tech-backend pull request #36
Opened 2024-11-13 12:08 UTC by McConderEz

2024-11-13 12:45 UTC, KirillSachkov requested changes

2024-11-14 11:53 UTC, McConderEz commented on backend/src/Shared/SachkovTech.Framework/Authorization/PermissionRequirementHandler.cs
> +        var userIdClaim = context.User.Claims.FirstOrDefault(c => c.Type == CustomClaims.Id)!.Value;
Я сделал через middleware, но столкнулся с проблемой, что в permission requirment handler я из скоупа достаю новый пустой экземпляр UserScopedData. Ну и в контроллерах я тоже тогда буду доставать пустой user scoped. В какую сторону копать, чтобы разобраться с этим?

2024-11-14 12:13 UTC, KirillSachkov requested changes

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Middlewares/AuthorizationMiddleware.cs
> +            var userScopedData = scope.ServiceProvider.GetRequiredService<UserScopedData>();
тебе здесь не нужно создавать скоуп, ты должен получить из di UserScopedData, это можно сделать через параметры метода InvokeAsync

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Middlewares/AuthorizationMiddleware.cs
> +            var userIdClaim = context.User.Claims.FirstOrDefault(c => c.Type == CustomClaims.Id)!.Value;
здесь лучше сделать проверку что value такое есть, если нет, то просто отправить дальше по конвееру

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Middlewares/AuthorizationMiddleware.cs
> +        try
в try catch это не нужно оборачивать, потому что он и так оборнут в try catch exceptionmiddleware

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Middlewares/AuthorizationMiddleware.cs
> +public class AuthorizationMiddleware
Давай назовём лучше UserScopedDataMiddleware

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Middlewares/AuthorizationMiddleware.cs
> +    public static IApplicationBuilder UseAuthorizationMiddleware(
UseUserScopedData

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Authorization/PermissionRequirementHandler.cs
> +        if (context.Resource is HttpContext httpContext &&
здесь всё таки не выйдет нормально получить доступ к UserScopedData, поэтому давай через context.User доставать данные, как и делали

2024-11-14 12:13 UTC, KirillSachkov commented on backend/src/SachkovTech.Web/Program.cs
> +app.UseAuthorizationMiddleware();
Из-за того, что не получится нормально доставать данные в permission handler давай тогда поместим его после авторизации

2024-11-15 19:32 UTC, McConderEz commented on backend/src/Shared/SachkovTech.Framework/Authorization/PermissionRequirementHandler.cs
> +        if (permissions.Contains(permission.Code))
Оставлять так?Или тот вариант с добавлением user scoped data в context Items? Вроде второй вариант лучше, не нужно опять делать выборку разрешений и парсить гуид, не?

2024-11-16 12:39 UTC, KirillSachkov requested changes

2024-11-16 12:39 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Authorization/PermissionRequirementHandler.cs
> +        if (permissions.Contains(permission.Code))
попробуй через IHttpContextAccessor, там вроде можно из di вытаскивать, только не забудь зарегать IHttpContextAccessor

2024-11-16 13:27 UTC, KirillSachkov requested changes

2024-11-16 13:27 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.Framework/Authorization/PermissionRequirementHandler.cs
> +        if (_httpContextAccessor.HttpContext.Items.TryGetValue("user-scoped-data", out var userScopedDataObj) &&
попробуй через .HttpContext.RequestServices, а не итемы

2024-11-16 13:30 UTC, KirillSachkov approved these changes

2024-11-16 13:30 UTC, merged