issue-46
SachkovTech/sachkov-tech-backend pull request #74
Opened 2024-11-23 18:08 UTC by haxnted

2024-11-23 18:11 UTC, haxnted commented
![image](https://github.com/user-attachments/assets/0c772e24-6206-4ca8-a055-0c5059bb1ff9)

2024-11-24 10:20 UTC, KirillSachkov requested changes

2024-11-24 10:20 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Lessons/GetLessonByIdTests/GetLessonByIdTests.cs
> +        var sut = Scope.ServiceProvider.GetRequiredService<IQueryHandlerWithResult<LessonResponse, GetLessonByIdQuery>>();
Sut можно вынести в поле, оно для всех тут тестов одно

2024-11-24 10:20 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Lessons/GetLessonWithPaginationTests/GetLessonWithPaginationTests.cs
> +    public async Task Get_lessons_with_pagination_should_return_paginated_list()
Не нужно в названии писать should return, достаточно того, что до этой фразы

2024-11-24 10:20 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Lessons/GetLessonWithPaginationTests/GetLessonWithPaginationTests.cs
> +    public async Task Get_lessons_with_invalid_query_should_return_error()
Тут лучше назвать Cant_get...

2024-11-24 10:20 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Lessons/GetLessonByIdTests/GetLessonByIdTests.cs
> +        var sut = Scope.ServiceProvider.GetRequiredService<IQueryHandlerWithResult<LessonResponse, GetLessonByIdQuery>>();
Сделать полем

2024-11-24 10:20 UTC, KirillSachkov commented on backend/src/Issues/SachkovTech.Issues.Application/Features/Lessons/Queries/GetLessonWithPagination/GetLessonsWithPaginationHandler.cs
> +            .ToList();
Может быть вместо создания нового pagedlist просто изменять Items, в других местах тоже проверь

2024-11-24 11:01 UTC, merged