Added integration tests for issue.
SachkovTech/sachkov-tech-backend pull request #88
Opened 2024-11-26 11:47 UTC by aznoran

2024-11-27 07:23 UTC, KirillSachkov requested changes

2024-11-27 07:23 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Issues/AddIssueTests/AddIssueTests.cs
> +        var sut = Scope.ServiceProvider.GetRequiredService<ICommandHandler<Guid, AddIssueCommand>>();
это можно вынести в поле, чтобы каждый раз не запрашивать

2024-11-27 07:23 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Issues/DeleteIssueTests/SoftDeleteIssueTests.cs
> +        var sut = Scope.ServiceProvider.GetRequiredService<SoftDeleteIssueHandler>();
можно вынести в поле

2024-11-27 07:23 UTC, KirillSachkov commented on backend/src/Issues/tests/SachkovTech.Issues.IntegrationTests/Issues/RestoreIssueTests/RestoreIssueTests.cs
> +        var sut = Scope.ServiceProvider.GetRequiredService<RestoreIssueHandler>();
поле

2024-11-27 13:58 UTC, aznoran commented
я вынес но не так как ты предполагал - причина в том что айди передавать айди, которые я получаю при сидировании и при вынесение айдишников из методов в поля только хаос создается а не гибкость, поправь если не прав

2024-11-28 08:11 UTC, KirillSachkov commented
> я вынес но не так как ты предполагал - причина в том что айди передавать айди, которые я получаю при сидировании и при вынесение айдишников из методов в поля только хаос создается а не гибкость, поправь если не прав

я имел в виду вынести sut в приватные полня, а не команды, то есть нужно вынести хэндлеры

2024-11-30 09:59 UTC, KirillSachkov requested changes
Можно пофиксить варнинги и после мержить

2024-11-30 10:41 UTC, KirillSachkov requested changes

2024-11-30 10:41 UTC, KirillSachkov commented on backend/src/Accounts/SachkovTech.Accounts.Application/Queries/UserQueryBuilder.cs
> +#pragma warning disable CS8603 // Possible null reference return.
можно попробовать решить через !

2024-11-30 10:41 UTC, KirillSachkov commented on backend/src/Accounts/SachkovTech.Accounts.Contracts/Dtos/RolePermissionDto.cs
> +    public RoleDto? Role { get; init; }
вместо добавление ? лучше написать = default!. Потому что мы знаем что оно не Null

2024-11-30 10:41 UTC, KirillSachkov commented on backend/src/Accounts/SachkovTech.Accounts.Contracts/Dtos/RolePermissionDto.cs
> +    public RoleDto? Role { get; init; }
везде аналогично

2024-11-30 10:41 UTC, KirillSachkov commented on backend/src/Accounts/SachkovTech.Accounts.Contracts/Dtos/UserDto.cs
> +    public string? Email { get; init; }
здесь лучше = string.Empty

2024-11-30 10:41 UTC, KirillSachkov commented on backend/src/Accounts/SachkovTech.Accounts.Domain/AdminAccount.cs
> +#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
лучше все поля на которые жалуется nullable сделать = default!

2024-11-30 18:32 UTC, KirillSachkov approved these changes

2024-11-30 20:03 UTC, merged